import './globals.css'
import { Raleway, Merriweather_Sans } from "@next/font/google";

const raleway = Raleway({
  variable: "--display-font",
  subsets:['cyrillic']
});

const merriweather = Merriweather_Sans({
  variable: "--body-font",
  subsets:['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${raleway.variable} ${merriweather.variable} bg-gray-100`}>
      <body >
        <div>
        {children}
        </div>
        </body>
    </html>
  )
}
